.umirc.ts, docs/demo/draw_line.jsx, package.json, src/modes/draw_feature.ts, src/modes/draw_mode.ts, src/modes/draw_polygon.ts, src/util/constant.ts
feat：
1、新增添加点事件  draw.addPoint
fix：
1·、修复cursor 从point mouseout的时候错误
2、修复绘制线时，无法拖拽问题
=> Feat yanxiong

docs/基础绘制/lineDrawer/API.md, docs/基础绘制/polygonDrawer/API.md, src/constants/event.ts, src/drawer/PolygonDrawer.ts, src/drawer/common/BaseLineDrawer.ts, src/interactive/dblclick.ts, src/interactive/index.ts, src/typings/drawer.ts, src/utils/calc.ts
- 新增控制距离和面积是否展示的参数 showOnNormal 和 showOnActive
- 修复在地图不同位置单击间隔过快误触发dblclick结束绘制的bug
=> Feat：新增控制距离和面积文本展示的参数/修复双击误触发问题

package.json, src/constant/event.ts, src/drawer/line-drawer.ts, src/drawer/polygon-drawer.ts, src/mode/base-mode.ts, src/mode/drag-polygon-mode.ts
- 修复initData覆盖setData数据问题
- setTimeout => requestAnimateFrame
=> fix: 修复clear方法未触发change事件

docs/docs/event.md, docs/docs/pointEvent.md, src/mode/base-mode.ts, src/render/layer-render.ts, src/render/scene-render.ts, src/source/source.ts
=> feat: 监听 Draw 的事件名支持字符串格式

docs/docs/method.md, package.json, src/drawer/circle-drawer.ts, src/drawer/line-drawer.ts, src/drawer/point-drawer.ts, src/drawer/polygon-drawer.ts, src/drawer/rect-drawer.ts, src/mode/base-mode.ts, src/mode/drag-polygon-mode.ts, src/mode/line-mode.ts, src/mode/polygon-mode.ts
=> feat: 新增设置激活 Feature 项的方法

.umirc.ts, README.md, package.json
=> docs: 1.将2.X版本的 L7Draw 文档部署在另外的 Github 站点上

docs/example/polygon/area.tsx, package.json, src/mode/line-mode.ts
=> fix: 修复dist入口文件指向问题

src/mode/line-mode.ts, src/mode/point-mode.ts, src/mode/polygon-mode.ts
=> fix: 修复 mousemove 时重复设置数据的问题

package.json
=> docs: update version 3.0.14

docs/docs/super/style.md, docs/example/point/style.tsx, package.json, src/constant/style.ts, src/render/mid-point-render.ts, src/render/point-render.ts, src/render/text-render.ts, src/typings/style.ts
=> fix: 修复点图层边框失效问题

package.json, src/render/mid-point-render.ts, src/render/point-render.ts, src/render/text-render.ts
=> fix: 修复 style 为空的报错问题

docs/docs/control.md, package.json, src/constant/event.ts, src/control/index.ts
=> feat: 新增 DrawControl 清空事件

.umirc.ts, docs/docs/control.md
=> docs: 菜单栏新增 L7Editor 入口

.umirc.ts
=> fix: 修复地图白屏问题

docs/example/map/baidu.md, docs/example/map/baidu.tsx, docs/example/map/gaode.md, docs/example/map/gaode.tsx, docs/example/map/mapbox.md, docs/example/map/mapbox.tsx, docs/example/map/tencent.md, docs/example/map/tencent.tsx, package.json, src/interactive/popup.ts, src/utils/common.ts
=> feat: 新增支持底图类型

README.md, package.json
=> docs: 更新文档相关说明

docs/docs/super/adsorb.md, src/mode/line-mode.ts, src/source/source.ts, src/utils/adsorb.ts, src/utils/feature.ts
=> feat: 通过 bbox 优化吸附计算性能

docs/example/common/bbox.tsx
=> docs: 完善 bbox 示例

README.md, src/drawer/line-drawer.ts, src/drawer/point-drawer.ts, src/mode/base-mode.ts, src/mode/polygon-mode.ts, src/utils/adsorb.ts
=> fix: 修复 Multi 数据获取问题

docs/example/control/enable-by-click.md, docs/example/control/enable-by-click.tsx, src/control/index.css, src/control/index.less, src/control/index.ts
=> fix: 修复 DrawControl 元素互斥问题

package.json, src/control/index.ts
=> fix: 修复 L7 升级导致的 inversify 缺失问题

.fatherrc.ts, package.json, src/utils/adsorb.ts
=> fix: 修复吸附点计算问题
